version: '2.1'
services:

  # active-mq МС ЕФР
  efr-mq:
    image: docker.dos.softlab.ru/rshb/efr/communication-systems/library/active-mq:0.0.1
    ports:
      - "8161:8161"
      - "61616:61616"

  # приложение api-gateway-app
  api-gateway-app:
    image: docker.dos.softlab.ru/smedservice/api-gateway/api-gateway-app:${PR_IMAGE_TAG}
    ports:
      - "8082:8080"
      - "9992:9990"
      - "8782:8787"
    links:
      - efr-mq

  # приложение auth-service-db
  auth-service-db:
    image: docker.dos.softlab.ru/smedservice/auth-service/auth-service-db:${PR_IMAGE_TAG}
    ports:
      - "5433:5432"

  # приложение auth-service-app
  auth-service-app:
    image: docker.dos.softlab.ru/smedservice/auth-service/auth-service-app:${PR_IMAGE_TAG}
    ports:
      - "8083:8080"
      - "9993:9990"
      - "8453:8453"
    links:
      - efr-mq
      - auth-service-db:service-db

  # приложение common-dict-db
  common-dict-db:
    build:
      context: ./common-dict-app
      dockerfile: Dockerfile-db
    image: docker.dos.softlab.ru/smedservice/common-dict/common-dict-db:${BUILD_IMAGE_TAG}
    ports:
      - "5432:5432"

  # приложение common-dict-app
  common-dict-app:
    build:
      context: ./common-dict-app
      dockerfile: Dockerfile-app.${BUILD_MODE:-dev}
    image: docker.dos.softlab.ru/smedservice/common-dict/${BUILD_MODE:-dev}/common-dict-app:${BUILD_IMAGE_TAG}
    ports:
      - "8080:7001"
      - "8450:8453"
    links:
      - efr-mq
      - efr-mq:logging-mq
      - common-dict-db:service-db
    volumes:
       - /share/.:/tmp/share

  # презентационная часть микросервиса common-dict
  web-presentation-app:
    image: docker.dos.softlab.ru/smedservice/common-dict-presentation/common-dict-presentation:${PR_IMAGE_TAG}
    env_file:
      - .env
    ports:
      - "8888:80"
    links:
      - api-gateway-app