/*
 * API микросервиса общих справочников
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.softlab.efr.common.client;

import ru.softlab.efr.common.dict.exchange.model.Bank;

import ru.softlab.efr.infrastructure.transport.client.*;
import ru.softlab.efr.common.utilities.rest.*;
import ru.softlab.efr.common.utilities.rest.client.*;
import ru.softlab.efr.common.utilities.rest.converters.DateParser;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import ru.softlab.efr.infrastructure.transport.client.impl.JmsUriBuilder;

import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.*;
import org.springframework.util.*;
import org.springframework.util.concurrent.ListenableFuture;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * Содержит методы для взаимодействия с приложением common-dict-app
 **/
@Component
public class BanksClient {
    private static final String REQUIRED_PARAM_ERROR = "Не указан обязательный параметр '%s' при вызове %s";
    private static final String APPLICATION_NAME = "common-dict-app";
    private static final String STATUS_CODE_TEMPLATE = "status code: [%s]";

    private final MicroServiceTemplate microServiceTemplate;

    /**
     * Возвращяет экземпляр класса
     * @param microServiceTemplate - объект, реализующий интерфейс {@link MicroServiceTemplate}
     */
    public BanksClient(MicroServiceTemplate microServiceTemplate) {
        this.microServiceTemplate = microServiceTemplate;
    }


    /**
     * Создание банка
     * POST /dictionaries/banks
     *
     * @param bank Данные о банке (required)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @return Созданный банк
     * @throws RestClientException в случае неудачи
    */
    public Bank createBank(Bank bank, long timeout) throws RestClientException {
        return createBank(bank).get(timeout);
    }

    /**
     * Создание банка асинхронно
     * POST /dictionaries/banks
     *
     * @param bank Данные о банке (required)
     * @return Созданный банк
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Bank> createBank(Bank bank) throws RestClientException {
        return new ClientRestResult<>(createBankInternal(bank), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Bank>> createBankInternal(Bank bank) throws RestClientException {
        if (bank == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "bank", "createBank"));
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/banks"));

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.POST, uriBuilder.build())
                  .body(bank);
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Bank>(){});
    }

    /**
     * Удаление банка
     * DELETE /dictionaries/banks/{id}
     *
     * @param id Идентификатор банка (required)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @throws RestClientException в случае неудачи
    */
    public Void deleteBank(Long id, long timeout) throws RestClientException {
        return deleteBank(id).get(timeout);
    }

    /**
     * Удаление банка асинхронно
     * DELETE /dictionaries/banks/{id}
     *
     * @param id Идентификатор банка (required)
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Void> deleteBank(Long id) throws RestClientException {
        return new ClientRestResult<>(deleteBankInternal(id), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Void>> deleteBankInternal(Long id) throws RestClientException {
        if (id == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "id", "deleteBank"));
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/banks/{id}")).variable("id", id);

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.DELETE, uriBuilder.build())
                  .build();
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Void>(){});
    }

    /**
     * Редактирование банка
     * PUT /dictionaries/banks/{id}
     *
     * @param id Идентификатор банка (required)
     * @param bank Данные о банке (required)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @return Сохраненный банк
     * @throws RestClientException в случае неудачи
    */
    public Bank editBank(Long id, Bank bank, long timeout) throws RestClientException {
        return editBank(id, bank).get(timeout);
    }

    /**
     * Редактирование банка асинхронно
     * PUT /dictionaries/banks/{id}
     *
     * @param id Идентификатор банка (required)
     * @param bank Данные о банке (required)
     * @return Сохраненный банк
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Bank> editBank(Long id, Bank bank) throws RestClientException {
        return new ClientRestResult<>(editBankInternal(id, bank), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Bank>> editBankInternal(Long id, Bank bank) throws RestClientException {
        if (id == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "id", "editBank"));
        if (bank == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "bank", "editBank"));
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/banks/{id}")).variable("id", id);

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.PUT, uriBuilder.build())
                  .body(bank);
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Bank>(){});
    }

    /**
     * Возвращает информацию о банке
     * GET /dictionaries/banks/{id}
     *
     * @param id Идентификатор банка (required)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @return Информация о банке
     * @throws RestClientException в случае неудачи
    */
    public Bank getBank(Long id, long timeout) throws RestClientException {
        return getBank(id).get(timeout);
    }

    /**
     * Возвращает информацию о банке асинхронно
     * GET /dictionaries/banks/{id}
     *
     * @param id Идентификатор банка (required)
     * @return Информация о банке
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Bank> getBank(Long id) throws RestClientException {
        return new ClientRestResult<>(getBankInternal(id), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Bank>> getBankInternal(Long id) throws RestClientException {
        if (id == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "id", "getBank"));
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/banks/{id}")).variable("id", id);

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.GET, uriBuilder.build())
                  .build();
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Bank>(){});
    }

    /**
     * Список банков
     * GET /dictionaries/banks
     *
     * @param bic БИК банка (optional)
     * @param name Наименование банка (optional)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @return Постраничный вывод результатов поиска
     * @throws RestClientException в случае неудачи
    */
    public RestPageImpl<Bank> listBanks(Pageable pageable, String bic, String name, long timeout) throws RestClientException {
        return listBanks(pageable, bic, name).get(timeout);
    }

    /**
     * Список банков асинхронно
     * GET /dictionaries/banks
     *
     * @param bic БИК банка (optional)
     * @param name Наименование банка (optional)
     * @return Постраничный вывод результатов поиска
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<RestPageImpl<Bank>> listBanks(Pageable pageable, String bic, String name) throws RestClientException {
        return new ClientRestResult<>(listBanksInternal(pageable, bic, name), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<RestPageImpl<Bank>>> listBanksInternal(Pageable pageable, String bic, String name) throws RestClientException {
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/banks"));

        addPageableParams(uriBuilder, pageable);
        if (bic != null)
            uriBuilder.param("bic", bic);
        if (name != null)
            uriBuilder.param("name", name);
        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.GET, uriBuilder.build())
                  .build();
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<RestPageImpl<Bank>>(){});
    }

    /**
     * Репликация банков
     * POST /dictionaries/banks/replication
     *
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @throws RestClientException в случае неудачи
    */
    public Void replicationBanks(long timeout) throws RestClientException {
        return replicationBanks().get(timeout);
    }

    /**
     * Репликация банков асинхронно
     * POST /dictionaries/banks/replication
     *
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Void> replicationBanks() throws RestClientException {
        return new ClientRestResult<>(replicationBanksInternal(), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Void>> replicationBanksInternal() throws RestClientException {
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/banks/replication"));

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.POST, uriBuilder.build())
                  .build();
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Void>(){});
    }
    private String cutComments(String path) {
        return path.split("#", 2)[0];
    }

    private void addPageableParams(MicroServiceURIBuilder builder, Pageable pageable) {
        if (pageable != null) {
            builder.param("page", pageable.getPageNumber());
            builder.param("size", pageable.getPageSize());
            Sort sort = pageable.getSort();
            if (sort != null) {
                List<String> sortParams = new ArrayList<>();
                for (Sort.Order next : sort) {
                    sortParams.add(next.getProperty());
                }
                sortParams.add(sort.getOrderFor(sortParams.get(0)).getDirection().name());
                builder.param("sort", String.join(",", sortParams));
            }
        }
    }

    private void processStatusCodeErrors(Exception e) throws RestClientException {
            HttpStatus statusCode = RestUtils.getStatusCode(e);
            if (statusCode != null) {
                switch (statusCode) {
                    case INTERNAL_SERVER_ERROR:
                        throw new RestClientException(String.format(STATUS_CODE_TEMPLATE, HttpStatus.INTERNAL_SERVER_ERROR.toString()));
                    case CONFLICT:
                        throw new EntityExistsException();
                    case NOT_FOUND:
                        throw new NotFoundException();
                }
            }
            throw new RestClientException(e.toString());
    }
}
