/*
 * API микросервиса общих справочников
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.softlab.efr.common.client;

import ru.softlab.efr.common.dict.exchange.model.Currency;

import ru.softlab.efr.infrastructure.transport.client.*;
import ru.softlab.efr.common.utilities.rest.*;
import ru.softlab.efr.common.utilities.rest.client.*;
import ru.softlab.efr.common.utilities.rest.converters.DateParser;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import ru.softlab.efr.infrastructure.transport.client.impl.JmsUriBuilder;

import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.*;
import org.springframework.util.*;
import org.springframework.util.concurrent.ListenableFuture;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * Содержит методы для взаимодействия с приложением common-dict-app
 **/
@Component
public class CurrenciesClient {
    private static final String REQUIRED_PARAM_ERROR = "Не указан обязательный параметр '%s' при вызове %s";
    private static final String APPLICATION_NAME = "common-dict-app";
    private static final String STATUS_CODE_TEMPLATE = "status code: [%s]";

    private final MicroServiceTemplate microServiceTemplate;

    /**
     * Возвращяет экземпляр класса
     * @param microServiceTemplate - объект, реализующий интерфейс {@link MicroServiceTemplate}
     */
    public CurrenciesClient(MicroServiceTemplate microServiceTemplate) {
        this.microServiceTemplate = microServiceTemplate;
    }


    /**
     * Создание валюты
     * POST /dictionaries/currencies
     *
     * @param currency Данные о валюте (required)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @return Созданная валюта
     * @throws RestClientException в случае неудачи
    */
    public Currency createCurrency(Currency currency, long timeout) throws RestClientException {
        return createCurrency(currency).get(timeout);
    }

    /**
     * Создание валюты асинхронно
     * POST /dictionaries/currencies
     *
     * @param currency Данные о валюте (required)
     * @return Созданная валюта
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Currency> createCurrency(Currency currency) throws RestClientException {
        return new ClientRestResult<>(createCurrencyInternal(currency), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Currency>> createCurrencyInternal(Currency currency) throws RestClientException {
        if (currency == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "currency", "createCurrency"));
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/currencies"));

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.POST, uriBuilder.build())
                  .body(currency);
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Currency>(){});
    }

    /**
     * Удаление валюты
     * DELETE /dictionaries/currencies/{id}
     *
     * @param id Идентификатор валюты (required)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @throws RestClientException в случае неудачи
    */
    public Void deleteCurrency(Long id, long timeout) throws RestClientException {
        return deleteCurrency(id).get(timeout);
    }

    /**
     * Удаление валюты асинхронно
     * DELETE /dictionaries/currencies/{id}
     *
     * @param id Идентификатор валюты (required)
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Void> deleteCurrency(Long id) throws RestClientException {
        return new ClientRestResult<>(deleteCurrencyInternal(id), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Void>> deleteCurrencyInternal(Long id) throws RestClientException {
        if (id == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "id", "deleteCurrency"));
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/currencies/{id}")).variable("id", id);

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.DELETE, uriBuilder.build())
                  .build();
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Void>(){});
    }

    /**
     * Редактирование валюты
     * PUT /dictionaries/currencies/{id}
     *
     * @param id Идентификатор валюты (required)
     * @param currency Данные о валюте (required)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @return Сохраненная валюта
     * @throws RestClientException в случае неудачи
    */
    public Currency editCurrency(Long id, Currency currency, long timeout) throws RestClientException {
        return editCurrency(id, currency).get(timeout);
    }

    /**
     * Редактирование валюты асинхронно
     * PUT /dictionaries/currencies/{id}
     *
     * @param id Идентификатор валюты (required)
     * @param currency Данные о валюте (required)
     * @return Сохраненная валюта
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Currency> editCurrency(Long id, Currency currency) throws RestClientException {
        return new ClientRestResult<>(editCurrencyInternal(id, currency), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Currency>> editCurrencyInternal(Long id, Currency currency) throws RestClientException {
        if (id == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "id", "editCurrency"));
        if (currency == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "currency", "editCurrency"));
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/currencies/{id}")).variable("id", id);

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.PUT, uriBuilder.build())
                  .body(currency);
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Currency>(){});
    }

    /**
     * Возвращает информацию о валюте
     * GET /dictionaries/currencies/{id}
     *
     * @param id Идентификатор валюты (required)
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @return Информация о валюте
     * @throws RestClientException в случае неудачи
    */
    public Currency getCurrency(Long id, long timeout) throws RestClientException {
        return getCurrency(id).get(timeout);
    }

    /**
     * Возвращает информацию о валюте асинхронно
     * GET /dictionaries/currencies/{id}
     *
     * @param id Идентификатор валюты (required)
     * @return Информация о валюте
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<Currency> getCurrency(Long id) throws RestClientException {
        return new ClientRestResult<>(getCurrencyInternal(id), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<Currency>> getCurrencyInternal(Long id) throws RestClientException {
        if (id == null)
            throw new RestClientException(String.format(REQUIRED_PARAM_ERROR, "id", "getCurrency"));
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/currencies/{id}")).variable("id", id);

        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.GET, uriBuilder.build())
                  .build();
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<Currency>(){});
    }

    /**
     * Список валют
     * GET /dictionaries/currencies
     *
     * @param timeout таймаут ожидания ответа на асинхронный запрос
     * @return Постраничный вывод результатов поиска
     * @throws RestClientException в случае неудачи
    */
    public RestPageImpl<Currency> listCurrencies(Pageable pageable, long timeout) throws RestClientException {
        return listCurrencies(pageable).get(timeout);
    }

    /**
     * Список валют асинхронно
     * GET /dictionaries/currencies
     *
     * @return Постраничный вывод результатов поиска
     * @throws RestClientException в случае неудачи
    */
    public ClientRestResult<RestPageImpl<Currency>> listCurrencies(Pageable pageable) throws RestClientException {
        return new ClientRestResult<>(listCurrenciesInternal(pageable), this::processStatusCodeErrors);
    }

    private ListenableFuture<ResponseEntity<RestPageImpl<Currency>>> listCurrenciesInternal(Pageable pageable) throws RestClientException {
        

        MicroServiceURIBuilder uriBuilder = JmsUriBuilder.service(APPLICATION_NAME)
            .path(cutComments("/dictionaries/currencies"));

        addPageableParams(uriBuilder, pageable);
        RequestEntity requestEntity = RequestEntity
                  .method(HttpMethod.GET, uriBuilder.build())
                  .build();
        return microServiceTemplate.exchange(requestEntity,
                    new ParameterizedTypeReference<RestPageImpl<Currency>>(){});
    }
    private String cutComments(String path) {
        return path.split("#", 2)[0];
    }

    private void addPageableParams(MicroServiceURIBuilder builder, Pageable pageable) {
        if (pageable != null) {
            builder.param("page", pageable.getPageNumber());
            builder.param("size", pageable.getPageSize());
            Sort sort = pageable.getSort();
            if (sort != null) {
                List<String> sortParams = new ArrayList<>();
                for (Sort.Order next : sort) {
                    sortParams.add(next.getProperty());
                }
                sortParams.add(sort.getOrderFor(sortParams.get(0)).getDirection().name());
                builder.param("sort", String.join(",", sortParams));
            }
        }
    }

    private void processStatusCodeErrors(Exception e) throws RestClientException {
            HttpStatus statusCode = RestUtils.getStatusCode(e);
            if (statusCode != null) {
                switch (statusCode) {
                    case INTERNAL_SERVER_ERROR:
                        throw new RestClientException(String.format(STATUS_CODE_TEMPLATE, HttpStatus.INTERNAL_SERVER_ERROR.toString()));
                    case CONFLICT:
                        throw new EntityExistsException();
                    case NOT_FOUND:
                        throw new NotFoundException();
                }
            }
            throw new RestClientException(e.toString());
    }
}
