############################################################
# Dockerfile to build common-dict-db container images
# Based on docker.dos.softlab.ru/rshb/efr/communication-systems/library/postgres:9.6
############################################################

# Use base docker.dos.softlab.ru/rshb/efr/communication-systems/library/postgres:9.6 image as the base
FROM docker.dos.softlab.ru/rshb/efr/communication-systems/library/postgres:9.6

# Load init scripts
# These initialization files will be executed in sorted name order as defined by the current locale.
ADD ./build/scripts/ ./build/test-data/  /docker-entrypoint-initdb.d/

# Add volumes
RUN mkdir -p /tmp/share
VOLUME /tmp/share