/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.common.dict.controllers;

import ru.softlab.efr.common.dict.exchange.model.Channel;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the Channels API
 */
public interface ChannelsApi {

    /**
     * Возвращает информацию о канале 
     * @param id Идентификатор канала  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/channels/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Channel> getChannel(@PathVariable("id") Long id) throws Exception;



    /**
     * Список каналов   
     * @param pageable параметры пагинации 
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/channels",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Page<Channel>> listChannels(@PageableDefault(value = 50) Pageable pageable) throws Exception;


}
