/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.common.dict.controllers;

import ru.softlab.efr.common.dict.exchange.model.Currency;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the Currencies API
 */
public interface CurrenciesApi {

    /**
     * Создание валюты 
     * @param currency Данные о валюте  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/currencies",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Currency> createCurrency(@Valid @RequestBody Currency currency) throws Exception;



    /**
     * Удаление валюты 
     * @param id Идентификатор валюты  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/currencies/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteCurrency(@PathVariable("id") Long id) throws Exception;



    /**
     * Редактирование валюты 
     * @param id Идентификатор валюты
     * @param currency Данные о валюте  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/currencies/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Currency> editCurrency(@PathVariable("id") Long id,@Valid @RequestBody Currency currency) throws Exception;



    /**
     * Возвращает информацию о валюте 
     * @param id Идентификатор валюты  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/currencies/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Currency> getCurrency(@PathVariable("id") Long id) throws Exception;



    /**
     * Список валют   
     * @param pageable параметры пагинации 
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/currencies",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Page<Currency>> listCurrencies(@PageableDefault(value = 50) Pageable pageable) throws Exception;


}
