/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.common.dict.controllers;

import ru.softlab.efr.common.dict.exchange.model.PrintTemplate;
import org.springframework.core.io.Resource;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the PrintTemplates API
 */
public interface PrintTemplatesApi {

    /**
     *  
     * @param content Шаблон формы  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/print-templates",
        method = RequestMethod.POST)
    ResponseEntity<PrintTemplate> create(@Valid @RequestPart(value="content", required=false) MultipartFile content) throws Exception;



    /**
     * Редактирование печатной формы 
     * @param type Тип печатной формы
     * @param copiesNumber Количество экземпляров при печати
     * @param content Шаблон формы  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/print-templates/{type}",
        method = RequestMethod.POST)
    ResponseEntity<String> edit(@PathVariable("type") String type,@NotNull  @Valid @RequestParam(value = "copiesNumber") Integer copiesNumber,@Valid @RequestPart(value="content", required=false) MultipartFile content) throws Exception;



    /**
     * Получение печатной формы по типу без контента 
     * @param type Тип печатной формы  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/print-templates/{type}",
        method = RequestMethod.GET)
    ResponseEntity<PrintTemplate> get(@PathVariable("type") String type) throws Exception;



    /**
     * Получить шаблон печатной формы по типу 
     * @param type Тип печатной формы  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/print-templates/{type}/content",
        produces = { "application/octet-stream" }, 
        method = RequestMethod.GET)
    ResponseEntity<Resource> getContent(@PathVariable("type") String type) throws Exception;



    /**
     * Список печатных форм   
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/print-templates",
        method = RequestMethod.GET)
    ResponseEntity<List<PrintTemplate>> list() throws Exception;


}
