/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.common.dict.controllers;

import ru.softlab.efr.common.dict.exchange.model.CheckTerroristRq;
import ru.softlab.efr.common.dict.exchange.model.CheckTerroristRs;
import org.springframework.core.io.Resource;
import ru.softlab.efr.common.dict.exchange.model.UpdateListStatus;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the Terrorists API
 */
public interface TerroristsApi {

    /**
     * Проверка паспортных данных по справочнику экстремистов/террористов 
     * @param checkTerroristRq Тело запроса проверки паспортных данных по справочнику экстремистов/террористов  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/terrorist/check",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CheckTerroristRs> checkTerrorist(@Valid @RequestBody CheckTerroristRq checkTerroristRq) throws Exception;



    /**
     * Получение текущего статуса процесса обновления справочника экстремистов/террористов   
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/terrorist/status",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<UpdateListStatus> getTerroristUpdateStatus() throws Exception;



    /**
     * Запрос обновления списка экстремистов/террористов   
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/terrorist/update",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<UpdateListStatus> updateTerroristList() throws Exception;



    /**
     *  
     * @param content DBF файл справочник террористов  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/dictionaries/terrorist/update",
        method = RequestMethod.POST)
    ResponseEntity<Void> uploadTerrorists(@Valid @RequestPart(value="content", required=false) MultipartFile content) throws Exception;


}
